server.port=8080
spring.application.name=lawtan-back

# ===================================================================
# Configuration Base de Données : Neon PostgreSQL
# ===================================================================
spring.datasource.url=jdbc:postgresql://ep-nameless-resonance-axyo4jaf-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_fjMht3i1XJBl

# Configuration JPA / Hibernate PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# Sécurité & JWT
# ===================================================================
lawtan.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
lawtan.jwt.expiration=86400000

# ===================================================================
# CORS
# ===================================================================
cors.allowed.origins=http://localhost:4200,http://127.0.0.1:4200,https://lawtan.vercel.app

# ===================================================================
# Documentation Swagger / OpenAPI
# ===================================================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
